FROM oraclelinux:9

# Update from repository
RUN dnf update -y

#Install PGADMIN4
dnf install -y https://ftp.postgresql.org/pub/pgadmin/pgadmin4/yum/pgadmin4-redhat-repo-2-1.noarch.rpm
dnf install -y pgadmin4
